### ISSUE TITLE
A configuration based network definition could be more useful instead of code based Network definition

### ISSUE THREAD

**Issue by ramukima** [kuujo/vertigo#1]
Do you envision adding a configuration based (may be JSON) Network Definition instead of a code based Network definition ?

**Comment by ramukima** [comment]
For example, if I consider a Network as a collection of "components" and "routes", its definition may look like -

"network": {
    "components": [
        "component": {
            "instance": 4,
            "id": "worker-id-1",
            "grouping": {
                "type": "FIELD",
                "field": "count"
            }
        },
        "component": {
            "instance": 2,
            "id": "worker-id-2",
            "grouping": {
                "type": "random"
            }
        },
        "component": {
            "instance": 1,
            "id": "worker-id-3",
            "grouping": {
                "type": "round-robin"
            }
        }
    ]
    "routes": [
        "route": {
            "from": "worker-id-1",
            "to": "worker-id-2"
        }
    ]
}

or something along those lines.

**Comment by yngbldjr** [comment]
+1 for json based definition.

The idea of having to compile code for the route definition is not as
appealing as pure json approach.

On Tuesday, October 29, 2013, ramukima wrote:

> For example, if I consider a Network as a collection of "components" and
> "routes", its definition may look like -
> 
> "network": {
> "components": [
> "component": {
> "instance": 4,
> "id": "worker-id-1",
> "grouping": {
> "type": "FIELD",
> "field": "count"
> }
> },
> "component": {
> "instance": 2,
> "id": "worker-id-2",
> "grouping": {
> "type": "random"
> }
> },
> "component": {
> "instance": 1,
> "id": "worker-id-3",
> "grouping": {
> "type": "round-robin"
> }
> }
> ]
> "routes": [
> "route": {
> "from": "worker-id-1",
> "to": "worker-id-2"
> }
> ]
> }
> 
> or something along those lines.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kuujo/vertigo/issues/1#issuecomment-27363319
> .

## 

Carter Youngblood
yngbldjr@gmail.com

**Comment by jhalterman** [comment]
...or YAML :)

**Comment by orolle** [comment]
I am working on a graphic network representation and than export this to json.
Will look similar like this: http://www.jointjs.com/demos/devs

**Comment by kuujo** [comment]
This has been implemented in the `componen-listeners` branch. Underlying the networks API is JSON (so that portions can be sent over the event bus for deployment), so this was simple to implement.

The new branch is going to be merged into master tonight. I will be posting an update in README explaining the changes (the network definition API has changed slightly to add more flexibility), and there will be documentation for constructing networks from JSON.

I'll close this issue when it's merged :-)

**Comment by kuujo** [comment]
By the way, before I merge it, feel free to take a look at the JSON documentation and make any suggestions:

https://github.com/kuujo/vertigo/tree/component-listeners#an-example-json-network

I was thinking I could provide a module for deploying networks via this method, e.g.

`vertx runmod net.kuujo~vertigo-network~0.1 -conf my-network.json`

The `net.kuujo~vertigo-network~0.1` module only needs to consist of a single verticle.

``` java
Network network = Network.fromJson(container.config());
cluster.deploy(network);
```

...but I haven't decided whether it's worth it to add that modules or let users do it themselves.

**Comment by kuujo** [comment]
That documentation has moved [here](https://github.com/kuujo/vertigo/wiki/Java-User-Manual#defining-networks-in-json)

I'm still interested in input if you have it.

**Comment by orolle** [comment]
I have some bigger modifications. Idea is to use the vertigo graph to orchestrate and monitor workflows between verticles. Therefore I modified the following code:
Components can suspend their acking - no ack timeout. This is for long running Tasks, like waiting for human approval (accept customer order). Might be good to add this in the in network json?
Graphical network editor (html + js) for designing processing graphs and workflows with ease.
Modifications I have to do:
Auditor gets performance monitoring functionality. Idea is to see latency, throughput, failures etc. of the vertigo processing. Later the auditor should be able to manage the processing network and scale up/down components if load balancing is necessary. Auditor might be customizable, like eg. Workers. The developer can than decide which features an Auditor should implement (monitoring, auto load balancing, transaction safety)
If processing of a message in vertigo fails, the components should be notified and be able to roll modifications back. I am not sure how to do this with vertigo, but its important in active databases and message-orientated-middlewares for transaction safety.

**Comment by kuujo** [comment]
I have indeed been considering exactly these types of features, and things like transactions, various other features for managing state, monitoring, etc. Some of this I would envision happening over the event bus as much as possible. Certainly, providing event bus based interfaces (JSON structures) as opposed to Java interfaces can make for much more flexible APIs and decouples systems from each other. For instance, I added the [events](https://github.com/kuujo/vertigo/wiki/Java-User-Manual#events) system precisely for things like monitoring (think Storm's hooks). Admittedly, it needs significantly more events, but ideally things like monitoring could be provided in separate projects that register event bus handlers.

One of the reasons I haven't gone too far into monitoring - as with cluster management - is because I know Tim Fox and others have talked a lot about monitoring APIs for Vert.x in general, and it's hard to predict where Vert.x core might go in the near future. I think Vertigo needs to do as much as possible to integrate with any existing monitoring (and other) modules or frameworks rather than creating its own.

That said, for other features like load balancing or transactions and other stateful features, there may be a number of potential approaches. Certainly, supporting custom auditors would be easy. But there are other options. The existing API is pretty flexible and it could be possible to build additional APIs on top of it. That may not be ideal - a pluggable auditor could be the right move - but I think the options should be weighed. Considering pluggable auditors, it may also be prudent to improve the pluggability of coordinators for managing deployment/undeployment of network verticles as well. Custom coordinators can be implemented right now, but it's admittedly not as flexible of an API as it could be (users would have to implement too much logic specific to how the internals of Vertigo works for my taste).

I would _love_ to see a complete list of ideas for additional reliability/monitoring/whatever features you could suggest. I'd like to take a look at all the options for implementing such features and APIs as well.

All that said, it's my primary goal is to _always_ ensure Vertigo integrates as cleanly as possible with the Vert.x API and other Vert.x modules and systems. I may have to talk to Tim Fox to try to get some sense of the direction of Vert.x core before some desired features can be implemented. Like I said, if a similar feature is going into core I think it's best to try to co-opt the work of Tim Fox and Normal Maurer and whoever else as much as possible, even if it means delaying the feature until they get around to it. Certainly transactions are something that will have to be implemented purely in Vertigo, but with plans for monitoring, distributed shared data, pluggable cluster managers, and other features in Vert.x, some features might have to wait.

**Comment by kuujo** [comment]
By the way:

```
Graphical network editor (html + js) for designing processing graphs and workflows with ease.
```

I do love this idea, and I'd definitely support such a module, but I think this is one that definitely belongs in a separate project. It would be pretty simple to create a module that is essentially an `HttpServer` that serves a web-based UI for creating, deploying, and monitoring networks. Using a `SockJSServer`, a network definition could be defined via the UI and constructed on the back end and deployed when the user is finished. I'm not much of a web UI guy though (though I do do jQuery UIs at work). I'd definitely be willing to put some time into integrating a UI with the Vertigo API though.

**Comment by ramukima** [comment]
It all looks great to me. Thanks a bunch for making it.

I agree with Jordan about the UI & monitoring being a feature augmentation to vertigo than showing their presence in the core API. But I like the idea of having a UI. I will wait for it.

I am eager to see Vertigo in the master Vert.x repo in some form. Jordan, any plans on following up with Tim on making that happen ?

What will further help a user of Vertigo is to have some real use cases and recommendations on when to use it and when not to, probably the 'what its best at'. Just the motivation about Storm does not give the complete idea. Vertigo does different things.

**Comment by kuujo** [comment]
I'm actually working on getting it into the Vert.x repo right now. It should be in there within the next couple of days. Currently waiting for it to sync with Maven central.

But I came back to comment on metrics. I actually played around with some ideas for implementing metrics support for Vertigo. In my mind, there are a couple of ways that users can "hook" into the system to aggregate interesting data about Vertigo components.

First, users can provide custom `Hook` implementations that may be attached to components when they're deployed. I actually implemented this in code to see what it would look like. This method has the advantage of code within each component instance actually performing aggregation of metrics. However, the major problem that I see with this is with class loaders. There are issues with users providing custom classes that will be loaded when a component instance is started. Namely, it's difficult to control whether the provided `Hook` class would even be available within the actual component instance once its deployed. Essentially, this would mean it's up to the user to ensure that classes are available within component implementations. But this conflicts with patterns in Vertigo that intend to abstract those types of details from component implementations. In other words, a component should not know that a certain `Hook` implementation should be available when the component is started. There may be a way around this, but it would still require a lot of work to achieve the same behavior across all language implementations because of the way the Vert.x class loader integrates with language modules.

The second option is, as you mentioned, expanding upon Vertigo's _coordinator_ and _auditor_ verticles to provide APIs for hooking into the information that flows through them. This would probably be much easier to manage since we have complete control over when and how those verticles are deployed. Certainly, the _coordinator_ and _auditor_ receive enough interesting information about networks and their components to be able to support aggregation of very interesting data. Auditors know every time a component creates, acks, or fails a message, and indeed may even be able to deduce more than that. Perhaps a mixture of APIs for reading data that passes through auditors and periodic events emitted from the _coordinator_ and component instances could suffice for useful metrics.

I also played around with the idea of a UI. I made a simple module that serves a single monitoring interface, and it opened my eyes to what types of metrics information needs to be made available to make such a tool useful.

You're right that the Storm comparison is not enough :-) Storm is simply a well known analogy. Indeed, Vertigo is quite significantly different than Storm in my opinion. It's really designed to be used within the context of larger Vert.x applications, as opposed to Storm being a standalone system. And I actually am beginning to use it in my day job. Sure, I'm a shameless Vert.x apologist, but I've found the fact that Vertigo's built on such a powerful platform to be extremely advantageous, which is why I want to preserve and promote the relationship between Vertigo and Vert.x APIs as much as possible rather than hiding Vert.x underneath Vertigo.

I'll definitely have to add some documentation on use cases and better examples. I think real world examples would be nice (I'd share my actual real world examples if I could). I always imagine the first thing users ask when they see a new project is _what can this do for me?_

**Comment by elhosin** [comment]
Amazing work. I just can't wait for all you've planned for Vertigo and see it on Vert.x repo.

**Comment by orolle** [comment]
sorry for posting so late. I was ill the last few days.

Event Bus (EB) related features for Monitoring, Transactions, Load Balancing, (time-based) Event Algebra:
Event-based approach: Vertigo should use as much functionality of the core EB as possible. Problem is, that we do not know what is planed for the future of the EB? Jordan, can you ask Tim Fox about his EB plans?
Imo Tim likes to have only the core functionality in the EB. Eg. safe message delivery through persistent message queues was a topic on the vertx mailing list. He wanted, that a message-safe implementation of EB should be a customized EB Module as an additional layer on top of the EB. So we could write an EB ourself and share it with the community via module. 
But you are totally right. He told that monitoring will be added in the vertx core, too. I think he did not added monitoring in the core atm, because it is hard to draw a clear line, what is core functionality and what should be in a customized EB module. 
Custom-Auditor-based approach: I like that approach because its fast to develop and unrelated to future of the EB. On the contrary, it might lower the smooth vertigo integration bc some features like monitoring and safe msg delivery could be duplicated in vertigo and the future vertx core.

I can write a requirement analysis for Monitoring, Transactions, Load Balancing, (time-depended) Event Algebra. Most of this is already researched and could be found in the literature. Do we have some a wiki or knowledge base system?

Graphical network editor / UI:
Yeah, it should be outside of vertigo core. We can join forces for that. I am not good in UI stuff but I know much about data visualization - eg. network graphs, visualizations for reporting and analytics.
I pitched a project named verticle.flow on the vertx mailing list 2 weeks ago. The idea of verticle.flow is to add some UI and workflow functionality to vertigo. I pitched it because I wanted community feedback as fast as possible. You can read the pitch here: https://groups.google.com/forum/?fromgroups=#!topic/vertx/Q1fql6BxYpg . Maybe we can merge some of verticle.flow ideas in vertigo core and/or plugins?

My current UI can be tried out here: http://bl.ocks.org/orolle/7417528 . Drag new circles from the circle from the top-left "abstract" circle. Mouse over a circle and ctrl + mouse drag links between circles. The underlying graph structure can be synchronized between browsers via Vertx-SockJS-Bridge and enables collaborative editing :-)
Next step is to add directed links and some kind of property window for (1) circles (= properties for vertigo components ; maybe some kind of js editor based on http://codemirror.net/) and (2) arrows (= event data structure emitted to the next component). Than export the network in vertigo-js project (generate source files, test stubs, etc.). Than I would add runtime monitoring for vertigo networks.

**Comment by ramukima** [comment]
The changes look great. Closing.
